### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by cjdduarte** [ijgnd/export_selected_cards_or_notes_from_browser_with_metadata_to_csv_or_xlsx#1]
![Screenshot_1](https://user-images.githubusercontent.com/42243532/69418605-c7ff2a80-0cf9-11ea-98b2-0a6c5372cc7b.jpg)

**Comment by ijgnd** [comment]
Thanks for the report.

Anki doesn't bundle the full standard library from python, see e.g. [here](https://anki.tenderapp.com/discussions/ankidesktop/31413-anki-216-module-cgi-removed).

I missed that Anki doesn't bundle the module Fraction because often I don't use the compiled version from Ankiweb. 

I have to bundle this module with the add-on. Since fractions is a python module that just imports common modules this shouldn't be a problem. I'll update on the weekend. Until this is fixed I unpublished it from ankiweb.

**Comment by cjdduarte** [comment]
OK, I'll be waiting for a new version. Thank you.
